### ISSUE TITLE
Full resolution conversion from raw to g

### ISSUE THREAD

**Issue by brunopolitano** [hepingood/adxl345#3]
According to the data sheet (page 4 - Specifications), when using 2g range we have 10 bits resolution regardless of the value FULL_RES bit. Flipping FULL_RES bit the output is not the same.

FULL_RES = 1
x: 0.012

FULL_RES = 0
x: 0.0117

~~I think~~ the problem is [here](https://github.com/hepingood/adxl345/blob/c277bbde7233e4918963723e84211f7001328b3c/src/driver_adxl345.c#L3396) when multiplying by 0.004f instead of 0.0039f which is the [right full resolution scale factor](https://github.com/analogdevicesinc/no-OS/blob/d8c4d94ef2186842df9e792aff18c02f30381d16/drivers/accel/adxl345/adxl345.h#L177).

**Comment by libdriver** [comment]
Thank you very much for your question.

According to the page 5 of /datasheet/adxl345 datasheet.pdf(Scale Factor at XOUT, YOUT, ZOUT):

When full resolution bit == 0, its scale factor is always 0.0039g.That means 2g has 10bits, 4g has 11bits, 8g has 12bits and 16g has 13bits.

When full resolution bit == 1, 2g, 4g, 8g and 16g each have 10bits.That means 2g scale factor is 0.0039g, 4g scale factor is 0.0039x2g, 8g scale factor is 0.0039x3g and 16g scale factor is 0.0039x4g.

Now we have fixed this bugs and thank you very much again.
